name: Publish nuget package

on:
  workflow_dispatch:
  push:
    paths:
      - "LucideBlazor/**.csproj"
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        projectName: [LucideBlazor]
    
    
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      
      # Setup dotnet 9
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0
      
      # Run the publishing action
      - name: Publish on version change
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: ${{ matrix.projectName }}/${{ matrix.projectName }}.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}